// Package migrations provides access to the SQL migrations used to set up a
// PostgreSQL database for the postgres Storer implementation.
//
// The contents of this package are generated by go-bindata to be easily
// includable in Go binaries that use the lockbox.dev/clients/storers/postgres
// package so they can be executed as part of service startup, if desired.
package migrations
